/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package de.mpg.mpi.inf.d5.yavi.wikipedia.export.schemas;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class YaviPageMetadata extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5919561911600817816L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"YaviPageMetadata\",\"namespace\":\"de.mpg.mpi.inf.d5.yavi.wikipedia.export.schemas\",\"fields\":[{\"name\":\"page_id\",\"type\":[\"null\",\"long\"]},{\"name\":\"title\",\"type\":[\"null\",\"string\"]},{\"name\":\"redirect\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.Long page_id;
  @Deprecated public java.lang.CharSequence title;
  @Deprecated public java.lang.CharSequence redirect;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public YaviPageMetadata() {}

  /**
   * All-args constructor.
   * @param page_id The new value for page_id
   * @param title The new value for title
   * @param redirect The new value for redirect
   */
  public YaviPageMetadata(java.lang.Long page_id, java.lang.CharSequence title, java.lang.CharSequence redirect) {
    this.page_id = page_id;
    this.title = title;
    this.redirect = redirect;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return page_id;
    case 1: return title;
    case 2: return redirect;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: page_id = (java.lang.Long)value$; break;
    case 1: title = (java.lang.CharSequence)value$; break;
    case 2: redirect = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'page_id' field.
   * @return The value of the 'page_id' field.
   */
  public java.lang.Long getPageId() {
    return page_id;
  }

  /**
   * Sets the value of the 'page_id' field.
   * @param value the value to set.
   */
  public void setPageId(java.lang.Long value) {
    this.page_id = value;
  }

  /**
   * Gets the value of the 'title' field.
   * @return The value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }

  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'redirect' field.
   * @return The value of the 'redirect' field.
   */
  public java.lang.CharSequence getRedirect() {
    return redirect;
  }

  /**
   * Sets the value of the 'redirect' field.
   * @param value the value to set.
   */
  public void setRedirect(java.lang.CharSequence value) {
    this.redirect = value;
  }

  /**
   * Creates a new YaviPageMetadata RecordBuilder.
   * @return A new YaviPageMetadata RecordBuilder
   */
  public static de.mpg.mpi.inf.d5.yavi.wikipedia.export.schemas.YaviPageMetadata.Builder newBuilder() {
    return new de.mpg.mpi.inf.d5.yavi.wikipedia.export.schemas.YaviPageMetadata.Builder();
  }

  /**
   * Creates a new YaviPageMetadata RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new YaviPageMetadata RecordBuilder
   */
  public static de.mpg.mpi.inf.d5.yavi.wikipedia.export.schemas.YaviPageMetadata.Builder newBuilder(de.mpg.mpi.inf.d5.yavi.wikipedia.export.schemas.YaviPageMetadata.Builder other) {
    return new de.mpg.mpi.inf.d5.yavi.wikipedia.export.schemas.YaviPageMetadata.Builder(other);
  }

  /**
   * Creates a new YaviPageMetadata RecordBuilder by copying an existing YaviPageMetadata instance.
   * @param other The existing instance to copy.
   * @return A new YaviPageMetadata RecordBuilder
   */
  public static de.mpg.mpi.inf.d5.yavi.wikipedia.export.schemas.YaviPageMetadata.Builder newBuilder(de.mpg.mpi.inf.d5.yavi.wikipedia.export.schemas.YaviPageMetadata other) {
    return new de.mpg.mpi.inf.d5.yavi.wikipedia.export.schemas.YaviPageMetadata.Builder(other);
  }

  /**
   * RecordBuilder for YaviPageMetadata instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<YaviPageMetadata>
    implements org.apache.avro.data.RecordBuilder<YaviPageMetadata> {

    private java.lang.Long page_id;
    private java.lang.CharSequence title;
    private java.lang.CharSequence redirect;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(de.mpg.mpi.inf.d5.yavi.wikipedia.export.schemas.YaviPageMetadata.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.page_id)) {
        this.page_id = data().deepCopy(fields()[0].schema(), other.page_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.redirect)) {
        this.redirect = data().deepCopy(fields()[2].schema(), other.redirect);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing YaviPageMetadata instance
     * @param other The existing instance to copy.
     */
    private Builder(de.mpg.mpi.inf.d5.yavi.wikipedia.export.schemas.YaviPageMetadata other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.page_id)) {
        this.page_id = data().deepCopy(fields()[0].schema(), other.page_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.redirect)) {
        this.redirect = data().deepCopy(fields()[2].schema(), other.redirect);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'page_id' field.
      * @return The value.
      */
    public java.lang.Long getPageId() {
      return page_id;
    }

    /**
      * Sets the value of the 'page_id' field.
      * @param value The value of 'page_id'.
      * @return This builder.
      */
    public de.mpg.mpi.inf.d5.yavi.wikipedia.export.schemas.YaviPageMetadata.Builder setPageId(java.lang.Long value) {
      validate(fields()[0], value);
      this.page_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'page_id' field has been set.
      * @return True if the 'page_id' field has been set, false otherwise.
      */
    public boolean hasPageId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'page_id' field.
      * @return This builder.
      */
    public de.mpg.mpi.inf.d5.yavi.wikipedia.export.schemas.YaviPageMetadata.Builder clearPageId() {
      page_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'title' field.
      * @return The value.
      */
    public java.lang.CharSequence getTitle() {
      return title;
    }

    /**
      * Sets the value of the 'title' field.
      * @param value The value of 'title'.
      * @return This builder.
      */
    public de.mpg.mpi.inf.d5.yavi.wikipedia.export.schemas.YaviPageMetadata.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.title = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'title' field has been set.
      * @return True if the 'title' field has been set, false otherwise.
      */
    public boolean hasTitle() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'title' field.
      * @return This builder.
      */
    public de.mpg.mpi.inf.d5.yavi.wikipedia.export.schemas.YaviPageMetadata.Builder clearTitle() {
      title = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'redirect' field.
      * @return The value.
      */
    public java.lang.CharSequence getRedirect() {
      return redirect;
    }

    /**
      * Sets the value of the 'redirect' field.
      * @param value The value of 'redirect'.
      * @return This builder.
      */
    public de.mpg.mpi.inf.d5.yavi.wikipedia.export.schemas.YaviPageMetadata.Builder setRedirect(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.redirect = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'redirect' field has been set.
      * @return True if the 'redirect' field has been set, false otherwise.
      */
    public boolean hasRedirect() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'redirect' field.
      * @return This builder.
      */
    public de.mpg.mpi.inf.d5.yavi.wikipedia.export.schemas.YaviPageMetadata.Builder clearRedirect() {
      redirect = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public YaviPageMetadata build() {
      try {
        YaviPageMetadata record = new YaviPageMetadata();
        record.page_id = fieldSetFlags()[0] ? this.page_id : (java.lang.Long) defaultValue(fields()[0]);
        record.title = fieldSetFlags()[1] ? this.title : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.redirect = fieldSetFlags()[2] ? this.redirect : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
